# Generated by Django 4.2.20 on 2025-05-12 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestorName', models.TextField(max_length=100)),
                ('requestorLastName', models.TextField(max_length=100)),
                ('creationDateTime', models.DateTimeField(auto_now_add=True)),
                ('idMachine', models.CharField(max_length=10)),
                ('area', models.CharField(max_length=100)),
                ('machineStopped', models.BooleanField()),
                ('attentionRequired', models.BooleanField()),
                ('problemDescriptoin', models.TextField(max_length=400)),
                ('receptionDateTime', models.DateTimeField()),
                ('personnelAsigned', models.CharField(max_length=100)),
                ('programmedDate', models.DateField()),
                ('problemObservations', models.TextField(max_length=400)),
                ('problemCuaseSolution', models.TextField(max_length=400)),
                ('scrapEquipment', models.BooleanField()),
                ('needCalibration', models.BooleanField()),
                ('problemCuaseSolutionDate', models.DateField()),
                ('usedParts1', models.CharField(max_length=100)),
                ('partNumber1', models.CharField(max_length=100)),
                ('description1', models.TextField(max_length=200)),
                ('usedParts2', models.CharField(max_length=100)),
                ('partNumber2', models.CharField(max_length=100)),
                ('description2', models.TextField(max_length=200)),
                ('usedParts3', models.CharField(max_length=100)),
                ('partNumber3', models.CharField(max_length=100)),
                ('description3', models.TextField(max_length=200)),
                ('coversInstalled', models.BooleanField()),
                ('interlocksTested', models.BooleanField()),
                ('gardsInstalled', models.BooleanField()),
                ('electricalConexions', models.BooleanField()),
                ('visualRevision', models.BooleanField()),
                ('areaCleaned', models.BooleanField()),
                ('airGasWaterConexion', models.BooleanField()),
                ('tagsInEquipment', models.BooleanField()),
                ('finalRevisionComments', models.TextField(max_length=400)),
                ('closeDate', models.DateField()),
            ],
        ),
    ]
