# Generated by Django 4.2.20 on 2025-05-12 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mantenimiento',
            old_name='problemDescriptoin',
            new_name='problemDescription',
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='requestorLastName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='requestorName',
            field=models.CharField(max_length=100),
        ),
    ]
