# Generated by Django 4.2.20 on 2025-05-12 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0002_rename_problemdescriptoin_mantenimiento_problemdescription_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreTecnico', models.CharField(max_length=100)),
                ('apellidoTecnico', models.CharField(max_length=100)),
            ],
        ),
    ]
