# Generated by Django 4.2.20 on 2025-05-13 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0004_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimiento',
            name='resportedDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
