# Generated by Django 4.2.20 on 2025-05-13 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0005_mantenimiento_resporteddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimiento',
            name='tech',
            field=models.CharField(default='No asignado', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='timeServiceEnd',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='timeServiceStart',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
