# Generated by Django 4.2.20 on 2025-05-13 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0006_mantenimiento_tech_mantenimiento_timeserviceend_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParteUsada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(max_length=255)),
                ('numero_parte', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('mantenimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partes', to='mantenimiento.mantenimiento')),
            ],
        ),
    ]
