# Generated by Django 4.2.20 on 2025-05-13 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0007_parteusada'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parteusada',
            old_name='origen',
            new_name='cantidad',
        ),
        migrations.RemoveField(
            model_name='mantenimiento',
            name='description1',
        ),
        migrations.RemoveField(
            model_name='mantenimiento',
            name='description2',
        ),
        migrations.RemoveField(
            model_name='mantenimiento',
            name='description3',
        ),
        migrations.RemoveField(
            model_name='mantenimiento',
            name='partNumber1',
        ),
        migrations.RemoveField(
            model_name='mantenimiento',
            name='partNumber2',
        ),
        migrations.RemoveField(
            model_name='mantenimiento',
            name='partNumber3',
        ),
        migrations.RemoveField(
            model_name='mantenimiento',
            name='usedParts1',
        ),
        migrations.RemoveField(
            model_name='mantenimiento',
            name='usedParts2',
        ),
        migrations.RemoveField(
            model_name='mantenimiento',
            name='usedParts3',
        ),
    ]
